### ISSUE TITLE
Add hummingbird and PantherX to staking_key chain var

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-core#1014]
PantherX: 13v9iGhjvQUtVaZXcFFRCEbL1nPR4R8QJowBgMUcaGM2v1aV6mn, mode: full

hummingbird: 14DdSjvEkBQ46xQ24LAtHwQkAeoUUZHfGCosgJe33nRQ6rZwPG3, mode: full

**Comment by cokes518** [comment]
activated on 9/29. thanks!

**Comment by vihu** [comment]
https://github.com/helium/miner/blob/master/audit/var-87.md
