### ISSUE TITLE
Add milesight, risingHF, browan/merry IOT to staking_key chain var

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-core#1046]
three new makers:

RisingHF
143QF5dTGyAg1FqaE85mPApvjauFU8fUy6wavirQfJJDgSkC4gn
mode: full

Browan/MerryIoT
14iLrXUuGVhb7w1P8X3iBvRwoT9oemgbDonm5VVZJk56TdV8NV1
mode: full

Milesight
13H6RpJojJjkqPRfzdrFBDbpYw4b3A6HyMxgGFRgXf31Nuwq4xJ
mode: full

**Comment by sdrive** [comment]
when browan miners will be available for sale ?
