### ISSUE TITLE
Transferred Packets not paying out Mining Rewards

### ISSUE THREAD

**Issue by bitlite** [helium/blockchain-core#1078]
I have noticed that Transferred Packets are sometimes not paying out for the packets transferred.  Could you please verify this and confirm why these transfer packets are not providing any rewards?
![image](https://user-images.githubusercontent.com/4667628/140875248-4fabf76a-34c7-446b-94fb-73be8290f38d.png)

![image](https://user-images.githubusercontent.com/4667628/140875433-cae3acd7-5842-4c47-bf69-95698cd573ac.png)

![image](https://user-images.githubusercontent.com/4667628/140875978-4138efd0-2084-4405-92a0-fb24a5ffc55c.png)

However, I also had 4 transferred packets and the rewards did not seem fitting for the transferred packets.
![image](https://user-images.githubusercontent.com/4667628/140875656-d8b1d6d1-2a06-4b6e-8071-62f7844b129f.png)

And here 1 single transfer almost equaled the 4 above.
![image](https://user-images.githubusercontent.com/4667628/140875895-55e5e548-2ec1-4d0a-bc8d-da4b285c9383.png)

I have had more transfers with missing rewards than actual rewarding transfers.
Please investigate this further to ensure miners are getting the rewards that are suppose to be there.  We should be getting at least 0.00000001 HNT every time we have a transferred packet activity.  We are not even getting this.

**Comment by ke6jjj** [comment]
This issue is quite old, and it's not clear, from the images provided, that payments really are being skipped. Feel free to re-open, @bitlite, if you still think this is an issue.
