### ISSUE TITLE
Introduce `bones_per_hnt` chain var

### ISSUE THREAD

**Issue by jthiller** [helium/blockchain-core#1145]
DeWi would like to introduce a chain ahead of the redenomination outlined in HIP39.

Proposed var name is `bones_per_hnt`
Value reflecting status quo is `100000000` bones

When the redenomination happens, we will seek to update the chain var to reflect the redenominated value.

**Comment by evanmcc** [comment]
This seems reasonable, but is there a place where we actually use this conversion factor, or would changing this be ceremonial?

**Comment by jthiller** [comment]
Yea great clarification.

By doing this on-chain we create a clearly defined source for exchanges, community apps, etc to make a clean transition during redenomination.

The current expectation is that we will be able to query the chain var value from the API during a migration period (a few days wrapping the redenomination date, currently targeting Feb 01). After the redenomination, developers would likely revert to statically defining the multiple.

Outside of redenomination, the fixed chain var has some value in allowing developers to have the continued source of truth for this multiple, as there have been some fat-finger accidents in the past.
