### ISSUE TITLE
sadeghi66

### ISSUE THREAD

**Issue by Sadeghi66** [helium/blockchain-core#1512]
#@
![photo_2023-01-13_23-37-48](https://user-images.githubusercontent.com/122616597/212463008-892945e1-d9f9-4b51-8f41-0c402435e6b1.jpg)
Hotspot Name

Handsome Paisley Porcupine
Hotspot b58 Address

14BdFHCG7BHMpnbJRAorvGPx1XQN2igCT4zdpKQjDuUpUKk2eoR

Discord Handle

No response

Hotspot Manufacturer

panther x

Removal Reason

I deployed my hotspot in real location and have no idea why I am on the denylist, please remove my hotspot from the denylist, thank you!

Modifications

No

Extra forwarders

No
#
![photo_2023-01-13_22-14-01](https://user-images.githubusercontent.com/122616597/212460043-b1a38f04-0da7-4533-9ed8-265e7dae9966.jpg)
![photo_2023-01-13_22-14-31](https://user-images.githubusercontent.com/122616597/212460044-3b1ef9a4-0c89-440e-b288-498f1c0582fa.jpg)

Extra antennas

[No]( #url)

Additional Information

The hotspot is deployed in real location and has no modification, I used stock antenna and connected with Ethernet cable and I put the hotspot by the window.

**Comment by Ryan-Goldstein** [comment]
This is not where to submit removal requests. Instructions to do that are here: https://docs.helium.com/mine-hnt/crowdspot/#submit-a-removal-request
