### ISSUE TITLE
Fix build status

### ISSUE THREAD

**Issue by CruiseMan** [helium/blockchain-core#604]
Hard to tell if current code is ready for deployment when build fail.

**Comment by CruiseMan** [comment]
Same as here https://github.com/helium/miner/issues/502

**Comment by evanmcc** [comment]
closing with the same rationale as https://github.com/helium/miner/issues/502

**Comment by CruiseMan** [comment]
> closing with the same rationale as [helium/miner#502](https://github.com/helium/miner/issues/502)

Great, instead of foxing issue you just closed. Interesting development Helium shows. This approach to solving problem, stopped me from buying your device.

**Comment by abhay** [comment]
@CruiseMan it looks like the explanation in helium/miner#502 is pretty clear on what the issues are currently and you're not providing any advice on how you'd like to improve here. Open to hearing about it but opening multiple issues and leaving snarky comments isn't productive. Happy to have a conversation about this on [Discord](https://discord.gg/helium) if you're so inclined. You can ping me there.

**Comment by CruiseMan** [comment]
> @CruiseMan it looks like the explanation in [helium/miner#502](https://github.com/helium/miner/issues/502) is pretty clear on what the issues are currently and you're not providing any advice on how you'd like to improve here. Open to hearing about it but opening multiple issues and leaving snarky comments isn't productive. Happy to have a conversation about this on [Discord](https://discord.gg/helium) if you're so inclined. You can ping me there.

@abhay Why not just simple fix it, rather arguing with me ?. I wish your team lead read this.

**Comment by abhay** [comment]
Very open to your future pull requests, @CruiseMan.

**Comment by CruiseMan** [comment]
It is in you best interest to fix it. I'm just want to have green build that i can run on my hardware.

**Comment by CruiseMan** [comment]
@abhay /ban

**Comment by CruiseMan** [comment]
You have 15 PR open, who since 2019, who develop software this way, close it or merge.

**Comment by abhay** [comment]
Thanks for your feedback. Looking forward to constructive criticism and code as per our contribution guidelines.
