### ISSUE TITLE
Implement HIPs 15 + 17: Beaconing and Hex Density Based Reward Scaling

### ISSUE THREAD

**Issue by abhay** [helium/blockchain-core#673]
https://github.com/helium/HIP/blob/master/0015-beaconing-rewards.md
https://github.com/helium/HIP/blob/master/0017-hex-density-based-transmit-reward-scaling.md

These two HIPs have been approved by the community. The Helium core team will be scoping and beginning work on this shortly. This ticket is to track progress towards implementation.

**Comment by vihu** [comment]
Both of these HIPs have been merged and deployed. Details [here](https://github.com/helium/hip). Closing
