### ISSUE TITLE
Implement HIP 12: Remote Location Asserts

### ISSUE THREAD

**Issue by abhay** [helium/blockchain-core#674]
https://github.com/helium/HIP/blob/master/0012-remote-location-assert.md

This HIP has been approved by the community but not been prioritized by the Helium core team. We believe that this would be a good first project for an external developer to tackle.

**Comment by abhay** [comment]
Some early work has been done on https://github.com/helium/proto/pull/41 and https://github.com/helium/blockchain-core/pull/519 but a member of the community can use these as a starting point and work with the core team to land on the appropriate transaction message.

**Comment by maco2035** [comment]
Hello!

I am wondering what the game plan for this hip is. I would like to add remote asserts. What I was planing was after the first nonce, the miners key will not need to sign it, only the owners key would need to sign it. I was wondering if this would be something that would be the correct way to make the changes to it. I understand this is going to be new assert system, (v2).

This will allow new hotspots to add it to the chain via V1, as I don't see any other way in the whole codebase where when you have the helium hotspot signing it off. 

Then when you want to make a change to the assert location, V1 can be used if you can get the hotspot to sign the transaction locally. Or the V2 method of just using the owner/wallet to sign it off.

If there is another way to go about it, or the logic is off, let me know. It seems pretty straight forward for me to code this up, as it is going to be more or less a duplicate of V1 without the signing from the hotspot.
Thanks!

**Comment by abhay** [comment]
This is complete.
