### ISSUE TITLE
Problem with state channel DC consumption

### ISSUE THREAD

**Issue by disk91** [helium/blockchain-core#763]
Hello, I have an issue on mt router ID : 11awcuSbVURPkXX3FbKC7KF6bgEPRZqqPzv1FTEYABMLttUr13E

on March 24th after the two state_channel creation, my DC balance was 2956372.
on March 28th one of the state_channel has expired and a new one has been created ; 202 DC has been consumed on this state_channel.

The state channel configuration have 50K DC blocked per SC

my new balance is 2823340 DC

the delta is 133032 DC I can't explain

I was expecting it to be 2956372 + ( 50000 - 202 ) - 35000 - 50000 = 2921170 but it is 2823340 difference is 97830

There has no new device registered during this period of time ( no xor transactions )

**Comment by disk91** [comment]
It makes no difference ...
I was expecting it to be 2956372 + ( 100000 - 202 ) - 35000 - 100000 = 2921170 but it is 2823340 difference is 97830

**Comment by disk91** [comment]
> blockchain_ledger_v1:config(sc_overcommit, Ledger).

```
(router@127.0.0.1)1> blockchain_ledger_v1:config(sc_overcommit, Ledger).
* 1: variable 'Ledger' is unbound
```
Can you tell me what is missing please ?

**Comment by vihu** [comment]
> > blockchain_ledger_v1:config(sc_overcommit, Ledger).
> 
> ```
> (router@127.0.0.1)1> blockchain_ledger_v1:config(sc_overcommit, Ledger).
> * 1: variable 'Ledger' is unbound
> ```
> 
> Can you tell me what is missing please ?

You're just missing assigning `Ledger` prior to calling the config function. Try this way:

```
(miner@127.0.0.1)1> blockchain_ledger_v1:config(sc_overcommit, blockchain:ledger()).
{ok,2}
```

**Comment by disk91** [comment]
Thank you

**Comment by disk91** [comment]
I'll try to detail this a bit more. It seems that Explorer DC balance and wallet DC balanced were not synced. This should be the reason of this problem. 
Right now, I've burned some HNT and the balance is equal on both side. I'll tell you more on the next state_channel renewal

**Comment by disk91** [comment]
I confirm the dc balance is correct on ledger. Explorer is not correctly counting the state_channel DC release until some noew HNT are burn.  we can close the issue here and I'll create a new one on explorer
