### ISSUE TITLE
Provide ability to stake multiple validators in single transaction

### ISSUE THREAD

**Issue by jdgemm** [helium/blockchain-core#816]
A core part of our validator go-to-market strategy is working with staking providers (such as Bison Trails).

Currently, to stake multiple validators requires multiple transactions. This is inefficient. 

Similar to how multi-payments are batched and sent in a single transaction, provide the ability to stake multiple validators in a single transaction.

**Comment by evanmcc** [comment]
I don't think that this is a good idea.  Perhaps we could do the batching on the wallet side?

**Comment by abhay** [comment]
> I don't think that this is a good idea. Perhaps we could do the batching on the wallet side?

We already have some of this going on with the wallet CLI. Ideally this should be good enough for launch. 

I think we should consider supporting multi-stake transactions (as other chains do) if we ever consider delegation or nomination. Our current model doesn't explicitly need that.

The only use case I think will still be tough will be the folks on Ledger hardware wallets. They'll need to individually sign each transaction still on the hardware device. But now we're talking about a % of a % of users.

**Comment by evanmcc** [comment]
I think that we have added support for this (making it easier, at least) in the wallet.
