### ISSUE TITLE
Data-Only Hotspots: update assert location and add gateway

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-core#826]
Add logic to set assert location for data-only hotspots to $5, and lower add_gateway to $10.

new naming convention:

Old → New
Light -> Data-Only Hotspots
Non Consensus → Light Hotspots
Full Hotspots → no change

**Comment by andymck** [comment]
@cokes518 can you confirm if the following fees are correct or not:

**Add GW fee**

dataonly -> $10
light -> $10
full -> $40

**Assert Location fee**

dataonly -> $5
light -> $5
full -> $10

**Comment by cokes518** [comment]
**Add GW fee**

dataonly -> $10
light -> ~$10~ $40
full -> $40

**Assert Location fee**

dataonly -> $5
light -> ~$5~ $10
full -> $10


Updated to show that lights should have the same fees as full.
