### ISSUE TITLE
> "dac8d0126697f1d64220315fd747e9c21a9b0af9822463df0c8f9edf80c57de4"

### ISSUE THREAD

**Issue by woahdy** [helium/blockchain-core#924]
> "dac8d0126697f1d64220315fd747e9c21a9b0af9822463df0c8f9edf80c57de4"

__Originally posted by @woahdy in https://github.com/blockparty-sh/slp-explorer/pull/413#discussion_r672999893__

__Originally posted by @woahdy in https://github.com/blockparty-sh/slp-explorer/issues/438__

**Comment by madninja** [comment]
Please stop spamming unrelated issues

**Comment by woahdy** [comment]
Sorry. Accident
