### ISSUE TITLE
Add pisces, clodpi, and linxdot to staking_key chainvar

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-core#932]
Pisces: 134C7Hn3vhfBLQZex4PVwtxQ2uPJH97h9YD2bhzy1W2XhMJyY6d
Mode: Full

ClodPi: 13XuP2DjHEHVkKguDDZD2ev5AeqMLuJ8UQ44efEcDmVTnBcvc6F
Mode: Full

Linxdot: 14eUfY1GsjK4WH6uZYoeagnFtigBKdvPruAXLmc5UsUMEDj3yib
Mode: Full

**Comment by madninja** [comment]
Don't forget to add to the staking mode mappings!

**Comment by vihu** [comment]
https://github.com/helium/miner/blob/master/audit/var-80.md
