### ISSUE TITLE
Consider switching from xor to fuse filter

### ISSUE THREAD

**Issue by mpope9** [helium/blockchain-core#948]
Hello,

I noticed that this repo is using the [exor_filter](https://github.com/mpope9/exor_filter). Recently, the successor library was released, the [efuse_filter](https://github.com/mpope9/efuse_filter). Fuse filters are measurably smaller and faster than xor filters. Only `fuse8` is supported, there is no `xor16` equivalent, however I believe that `fuse8` has an even lower false positive rate than `xor16` but I am not 100% sure on that as the research paper has yet to be released. It also does not support a custom hashing function yet, but that can be added.

**Comment by Vagabond** [comment]
Ah, this is very interesting. Our use of xor filters is a bit integral to the system right now but maybe once the new library has some more hours on it and we can get a feel for the false positive rate we could look into switching.

**Comment by mpope9** [comment]
Makes sense, sounds good!
