### ISSUE TITLE
RAK hotspots keep syncing for over 4 days 

### ISSUE THREAD

**Issue by rami202** [helium/blockchain-core#958]
I own 5 Rak hotspots that have been online for like 4 months until the 18th of august when all of a sudden, 4/5 hotspots jumped into the syncing  and won't fully sync to the blockchain.

I have already done the following steps:

-Port forwarding is open
-Ethernet cable is plugged in
-Device and router have been turned off and on for like 10 times 

No earning and no beacons, however in and outbound are green, so could you please help me?

**Comment by abhay** [comment]
Please see the latest update on Discord.

**Comment by rami202** [comment]
what is the latest update?? i don't see anything could you please clarify?
