### ISSUE TITLE
Oracle Update

### ISSUE THREAD

**Issue by Scottsigel** [helium/blockchain-core#968]
The DeWi has solicited and verified a new group of price oracle submitters that we would like to add on chain:

- 13ZGgWX4Ajz9g9t3tM9ohDyso12o2E2CpYbMF2RBaT93rj7souE
- 1489qpKWAoLrURcaQEM1wJEViD4mk9WcqZMGhiTFfNGmaz8NFdX
- 14hntpRicek9pxzHBDPVWPwYHHmExrksaxzAsTjjstgLfnfG5Ve
- 14aQaRARuwLTLHLygiDNNapKZ7bcLSyXhHq9DeZ5kB2dnCxiiKv

We'd like to remove the following oracles for inactivity:

- 14t33QjopqCUVr8FXG4sr58FTu5HnPwGBLPrVK1BFXLR3UsnQSn
- 13Btezbvbwr9LhKmDQLgBnJUgjhZighEjNPLeu79dqBbmXRwoWm

DeWi contacted prospective oracles privately to preserve anonymity. This group was individually instructed to set up a dedicated server and mainnet wallet exclusively for the purpose of submitting price data. DeWi witnessed failed transactions from all four of the proposed new oracles above. Once the oracles are added on-chain, they'll be required to submit prices at a minimum of twice per day although most are expected to report more frequently.

**Comment by abhay** [comment]
I can confirm that some of these oracles have submitted transactions that are failing (as expected):

```
I, [2021-08-24T14:43:58.685353 #21896]  INFO -- : Checking: 13ZGgWX4Ajz9g9t3tM9ohDyso12o2E2CpYbMF2RBaT93rj7souE
I, [2021-08-24T14:43:58.785601 #21896]  INFO -- : ["2021-08-24T20:00:08.879704Z-{invalid,not_a_member}-$23.41", "2021-08-24T19:00:09.343179Z-{invalid,not_a_member}-$23.43", "2021-08-24T17:00:09.467495Z-{invalid,not_a_member}-$22.82", "2021-08-24T16:00:10.253403Z-{invalid,not_a_member}-$23.30", "2021-08-24T14:00:09.746237Z-{invalid,not_a_member}-$23.53"]
I, [2021-08-24T14:43:59.785997 #21896]  INFO -- : Checking: 1489qpKWAoLrURcaQEM1wJEViD4mk9WcqZMGhiTFfNGmaz8NFdX
I, [2021-08-24T14:43:59.849438 #21896]  INFO -- : ["2021-08-21T13:00:06.255149Z-{invalid,not_a_member}-$23.31", "2021-08-21T12:57:24.814036Z-{invalid,not_a_member}-$23.19"]
I, [2021-08-24T14:44:00.852625 #21896]  INFO -- : Checking: 14hntpRicek9pxzHBDPVWPwYHHmExrksaxzAsTjjstgLfnfG5Ve
I, [2021-08-24T14:44:00.953515 #21896]  INFO -- : ["2021-08-24T21:30:03.014936Z-{invalid,not_a_member}-$23.44", "2021-08-24T21:15:02.255372Z-{invalid,not_a_member}-$23.32", "2021-08-24T21:00:02.241736Z-{invalid,not_a_member}-$23.50", "2021-08-24T20:45:02.643575Z-{invalid,not_a_member}-$23.58", "2021-08-24T20:30:02.187899Z-{invalid,not_a_member}-$23.56"]
I, [2021-08-24T14:44:01.956183 #21896]  INFO -- : Checking: 14aQaRARuwLTLHLygiDNNapKZ7bcLSyXhHq9DeZ5kB2dnCxiiKv
I, [2021-08-24T14:44:02.031652 #21896]  INFO -- : ["2021-08-24T18:37:33.326209Z-{invalid,not_a_member}-$23.03", "2021-08-24T03:44:28.431958Z-{invalid,not_a_member}-$25.35", "2021-08-21T02:25:54.709777Z-{invalid,not_a_member}-$23.87"]
```

Three of them also seem to have some automation around it. Would like to see some more submissions from `1489qpKWAoLrURcaQEM1wJEViD4mk9WcqZMGhiTFfNGmaz8NFdX` but the rest seem okay.

Agree on the removals. They haven't been submitted prices on chain in a long time.

**Comment by abhay** [comment]
cc: @evanmcc @Vagabond for their thoughts.

**Comment by Vagabond** [comment]
I approve this message.

**Comment by abhay** [comment]
This has been deployed: https://github.com/helium/miner/blob/master/audit/var-83.md

**Comment by Scottsigel** [comment]
DeWi has another contributor here: 13s9hgVG78faxGXKwCoyY5vSUEnaf52QUC11wnGWEL8gAE9bNF3

**Comment by abhay** [comment]
> @Vagabond DeWi has another contributor here: 13s9hgVG78faxGXKwCoyY5vSUEnaf52QUC11wnGWEL8gAE9bNF3

@Scottsigel let's create new tickets for new ones.
