### ISSUE TITLE
Add Controllino, Heltec, and FreedomFi to staking_key chainvar

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-core#977]
Controllino: 14go8hvEDnotWTyhYv6Hu5PTnRUAQzJqbB6dsDm1oThkCcZe9zd, mode: Full
Heltec Automation: 14iC6N1HkqUjH7WEChHVQhPqJ1hbWBKpZXZVeHHykCA7tNDYF2C, mode: Full
FreedomFi: 13y2EqUUzyQhQGtDSoXktz8m5jHNSiwAKLTYnHNxZq2uH5GGGym, mode: Full

**Comment by abhay** [comment]
Deployed: https://github.com/helium/miner/blob/master/audit/var-83.md
